# config/packages/security.yaml
security:
    access_control:
       #- { path: ^/admin, roles: ROLE_ADMIN }
       - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_USER] }
       #- { path: ^/profile, roles: ROLE_USER }
    providers:
        mon_login:
            entity:
                class: App\Entity\Artists
                property: pseudo
    firewalls:
        main:
            security: true
            pattern: ^/
            anonymous: ~
            provider: mon_login
            form_login:
                login_path: login
                check_path: login
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /admin
                post_only:      true
            logout:
                path:   logout
                target: login
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    encoders:
        App\Entity\Artists:
            algorithm: bcrypt
